# Database Configuration
database:
  type: "sqlite"  # sqlite hoặc mysql
  sqlite:
    path: "plugins/LeDatAntiOP/data.db"
  mysql:
    host: "103.82.24.7"
    port: 3306
    database: "zcltyyu_antiop"
    username: "zcltyyu_admin"
    password: "Sqrtfl0@t01"
    use-ssl: false

# Discord Configuration
discord:
  token: ""
  guild-id: ""
  channel-id: ""
  command-channel-id: ""

# Dangerous Permissions (có thể config)
dangerous-permissions:
  - "bukkit.*"
  - "cmi.*"
  - "worldguard.*"
  - "worldedit.*"
  - "fawe.*"
  - "permissions.*"
  - "luckperms.*"
  - "luckperms.editor"
  - "luckperms.applyedits"
  - "towny.*"
  - "protocol.admin"
  - "placeholderapi.admin"
  - "playerpoints.*"
  - "serverprotector.admin"
  - "fawe.bypass"
  - "luckperms.sync"
  - "worldedit.generation.sphere"

dangerous-commands:
  - "//sphere"
  - "//pyramid"
  - "//cyl"
  - "//walls"
  - "//faces"
  - "//fill"
  - "//replace"
  - "//set"
  - "/sudo"
  - "/eco reset"
  - "/eco set"
  - "/p giveall"
  - "/pp giveall"
  - "/playerpoints giveall"
  - "/lp user"
  - "/lp group"
  - "/luckperms user"
  - "/luckperms group"
  - "/pex user"
  - "/pex group"
  - "/permissions user"
  - "/permissions group"
  - "/clearinventory"
  - "/clear"
  - "/powertool"
  - "/pt"
  - "/mute"
  - "/op"
  - "/deop"

# Discord Commands: antiop, checkip, resetip, listips, ban, unban