name: Build and Release

on:
  push:
    tags:
      - '-*'  # Chạy khi bạn push tag bắt đầu bằng v, ví dụ v1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build JAR with Gradle
        run: ./gradlew clean shadowJar

      - name: Create GitHub Release and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
